// Code generated by protoc-gen-go.
// source: blockchain.proto
// DO NOT EDIT!

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	blockchain.proto

It has these top-level messages:
	Block
	Blocks
	Empty
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Block struct {
	Data       []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Hash       []byte `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Nonce      []byte `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ParentHash []byte `protobuf:"bytes,4,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
}

func (m *Block) Reset()                    { *m = Block{} }
func (m *Block) String() string            { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()               {}
func (*Block) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Block) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Block) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Block) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *Block) GetParentHash() []byte {
	if m != nil {
		return m.ParentHash
	}
	return nil
}

type Blocks struct {
	Blocks []*Block `protobuf:"bytes,1,rep,name=blocks" json:"blocks,omitempty"`
}

func (m *Blocks) Reset()                    { *m = Blocks{} }
func (m *Blocks) String() string            { return proto.CompactTextString(m) }
func (*Blocks) ProtoMessage()               {}
func (*Blocks) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Blocks) GetBlocks() []*Block {
	if m != nil {
		return m.Blocks
	}
	return nil
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto.RegisterType((*Block)(nil), "main.Block")
	proto.RegisterType((*Blocks)(nil), "main.Blocks")
	proto.RegisterType((*Empty)(nil), "main.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Blockchain service

type BlockchainClient interface {
	Get(ctx context.Context, in *Block, opts ...grpc.CallOption) (*Blocks, error)
	Announce(ctx context.Context, in *Block, opts ...grpc.CallOption) (*Empty, error)
}

type blockchainClient struct {
	cc *grpc.ClientConn
}

func NewBlockchainClient(cc *grpc.ClientConn) BlockchainClient {
	return &blockchainClient{cc}
}

func (c *blockchainClient) Get(ctx context.Context, in *Block, opts ...grpc.CallOption) (*Blocks, error) {
	out := new(Blocks)
	err := grpc.Invoke(ctx, "/main.Blockchain/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainClient) Announce(ctx context.Context, in *Block, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/main.Blockchain/Announce", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Blockchain service

type BlockchainServer interface {
	Get(context.Context, *Block) (*Blocks, error)
	Announce(context.Context, *Block) (*Empty, error)
}

func RegisterBlockchainServer(s *grpc.Server, srv BlockchainServer) {
	s.RegisterService(&_Blockchain_serviceDesc, srv)
}

func _Blockchain_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Block)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.Blockchain/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainServer).Get(ctx, req.(*Block))
	}
	return interceptor(ctx, in, info, handler)
}

func _Blockchain_Announce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Block)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainServer).Announce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.Blockchain/Announce",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainServer).Announce(ctx, req.(*Block))
	}
	return interceptor(ctx, in, info, handler)
}

var _Blockchain_serviceDesc = grpc.ServiceDesc{
	ServiceName: "main.Blockchain",
	HandlerType: (*BlockchainServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Blockchain_Get_Handler,
		},
		{
			MethodName: "Announce",
			Handler:    _Blockchain_Announce_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "blockchain.proto",
}

func init() { proto.RegisterFile("blockchain.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 204 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x3d, 0xaf, 0x82, 0x30,
	0x14, 0x86, 0xc3, 0xe5, 0xe3, 0xde, 0x1c, 0x18, 0x6e, 0x4e, 0x1c, 0x1a, 0x17, 0x09, 0x3a, 0xb0,
	0xc8, 0x80, 0xbf, 0x40, 0x12, 0xa3, 0x33, 0x71, 0x37, 0x05, 0x31, 0x25, 0x4a, 0x4b, 0x68, 0x1d,
	0xfc, 0xf7, 0xa6, 0x07, 0x62, 0x70, 0x3b, 0xef, 0xfb, 0xf4, 0xb4, 0x4f, 0x0a, 0xff, 0xd5, 0x43,
	0xd5, 0xf7, 0x5a, 0xf0, 0x56, 0x66, 0xfd, 0xa0, 0x8c, 0x42, 0xaf, 0xe3, 0xad, 0x4c, 0x6e, 0xe0,
	0x17, 0x96, 0x20, 0x82, 0x77, 0xe5, 0x86, 0x33, 0x27, 0x76, 0xd2, 0xa8, 0xa4, 0xd9, 0x76, 0x82,
	0x6b, 0xc1, 0x7e, 0xc6, 0xce, 0xce, 0xb8, 0x00, 0x5f, 0x2a, 0x59, 0x37, 0xcc, 0xa5, 0x72, 0x0c,
	0xb8, 0x82, 0xb0, 0xe7, 0x43, 0x23, 0xcd, 0x85, 0x16, 0x3c, 0x62, 0x30, 0x56, 0x27, 0xae, 0x45,
	0xb2, 0x85, 0x80, 0xde, 0xd1, 0xb8, 0x86, 0x80, 0x5c, 0x34, 0x73, 0x62, 0x37, 0x0d, 0xf3, 0x30,
	0xb3, 0x22, 0x19, 0xd1, 0x72, 0x42, 0xc9, 0x2f, 0xf8, 0x87, 0xae, 0x37, 0xaf, 0xfc, 0x0c, 0x50,
	0x7c, 0xcc, 0x31, 0x06, 0xf7, 0xd8, 0x18, 0x9c, 0xaf, 0x2c, 0xa3, 0x59, 0xd0, 0xb8, 0x81, 0xbf,
	0xbd, 0x94, 0xea, 0x69, 0xa5, 0xbe, 0x8e, 0x4d, 0x81, 0x6e, 0xad, 0x02, 0xfa, 0x82, 0xdd, 0x3b,
	0x00, 0x00, 0xff, 0xff, 0xec, 0xd8, 0x38, 0x41, 0x16, 0x01, 0x00, 0x00,
}
